### KELOMPOK 10 :
1. MUHAMMAD ADE SULISTIANSYAH - 103102400045
2. IZAM ROSIAWAN - 103102400049
3. NOVENA AURELIA LUISMA - 103102400050
4. FEYSHA KAMILA PRACILYA - 103102400054

### Mengenali Karakteristik Data

Mengenali karakteristik data merupakan langkah awal yang sangat penting sebelum melakukan analisis data lebih lanjut. Proses ini dilakukan untuk memahami sifat dan ciri-ciri data yang dimiliki, seperti jenis data (apakah data tersebut berupa angka atau kategori), skala pengukuran (misalnya data nominal, ordinal, interval, atau rasio), serta bagaimana data tersebut tersebar.

In [3]:
#Data bertipe integer
umur = 19
print("Umur:", umur, "| Tipe data:", type(umur))

# Data bertipe float
tinggi = 175.5
print("Tinggi:", tinggi, "| Tipe data:", type(tinggi))

# Data bertipe string
nama = "Izam"
print("Nama:", nama, "| Tipe data:", type(nama))

# Data bertipe boolean
mahasiswa = True
print("Mahasiswa:", mahasiswa, "| Tipe data:", type(mahasiswa))

Umur: 19 | Tipe data: <class 'int'>
Tinggi: 175.5 | Tipe data: <class 'float'>
Nama: Izam | Tipe data: <class 'str'>
Mahasiswa: True | Tipe data: <class 'bool'>


### Tipe Data




Tipe data adalah suatu atribut atau jenis yang menentukan macam nilai apa yang bisa disimpan dalam sebuah variabel atau struktur data di komputer. Dalam konteks data dan pemrograman, tipe data sangat penting karena setiap jenis data memiliki karakteristik dan cara perlakuan yang berbeda. Misalnya, tipe data integer digunakan untuk bilangan bulat, float untuk bilangan desimal, string untuk teks atau karakter, dan boolean untuk nilai benar atau salah (True/False).

In [1]:
# Integer
angka = 10
print("Tipe data angka:", type(angka))

# Float
desimal = 3.14
print("Tipe data desimal:", type(desimal))

# String
teks = "Halo Dunia"
print("Tipe data teks:", type(teks))

# Boolean
benar_salah = True
print("Tipe data boolean:", type(benar_salah))

Tipe data angka: <class 'int'>
Tipe data desimal: <class 'float'>
Tipe data teks: <class 'str'>
Tipe data boolean: <class 'bool'>


### Membuat Array Dengan Berbagai Teknik

Membuat array dengan berbagai teknik berarti kita bisa membentuk kumpulan data (array) dengan cara yang berbeda-beda sesuai kebutuhan. Misalnya, kita bisa membuat array dari daftar (list) biasa yang sudah diisi nilai, seperti daftar angka atau nama. Selain itu, kita juga bisa membuat array yang semua elemennya sama, misalnya semua bernilai nol atau satu. Ada juga teknik membuat array dengan urutan angka tertentu, seperti angka 0 sampai 10, atau dengan jarak tertentu di antara angkanya.

In [4]:
# Array dari list biasa
angka = [1, 2, 3, 4, 5]
print("Array dari list biasa:", angka)

# Array dengan nilai yang sama
nol = [0, 0, 0, 0, 0]
print("Array dengan semua elemen nol:", nol)

# Array urutan angka dengan perulangan
urutan = []
for i in range(1, 6):
    urutan.append(i)
print("Array urutan angka 1 sampai 5:", urutan)

# Array dengan nilai acak sederhana
acak = [3, 1, 4, 2, 5]
print("Array nilai acak sederhana:", acak)

Array dari list biasa: [1, 2, 3, 4, 5]
Array dengan semua elemen nol: [0, 0, 0, 0, 0]
Array urutan angka 1 sampai 5: [1, 2, 3, 4, 5]
Array nilai acak sederhana: [3, 1, 4, 2, 5]


### Membuat Matriks

Membuat matriks berarti menyusun data dalam bentuk baris dan kolom, seperti tabel. Matriks biasanya digunakan untuk menyimpan data yang terstruktur, misalnya nilai siswa dalam beberapa mata pelajaran, di mana setiap baris mewakili siswa dan setiap kolom mewakili mata pelajaran. Dengan matriks, kita bisa dengan mudah melakukan operasi matematika atau analisis data, seperti penjumlahan, perkalian, atau mencari rata-rata.

In [5]:
# Matriks adalah list di dalam list
matriks = [
    [1, 2, 3],
    [4, 5, 6]
]

# Menampilkan matriks
print("Matriks 2x3:")
for baris in matriks:
    print(baris)

Matriks 2x3:
[1, 2, 3]
[4, 5, 6]


### MEMANIPULASI MATRIKS DAN OPERASI OPERASI MATRIKS

Matriks dapat dimanipulasi dengan berbagai cara, misalnya:

* Penjumlahan → menjumlahkan tiap elemen.

* Perkalian elemen → mengalikan elemen yang posisinya sama.

* Perkalian matriks → perkalian sesuai aturan aljabar linear.

* Transpose → membalik baris jadi kolom.

In [ ]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Penjumlahan:\n", A + B)
print("Perkalian Elemen:\n", A * B)
print("Perkalian Matriks:\n", np.dot(A, B))
print("Transpose A:\n", A.T)


Penjumlahan:
 [[ 6  8]
 [10 12]]
Perkalian Elemen:
 [[ 5 12]
 [21 32]]
Perkalian Matriks:
 [[19 22]
 [43 50]]
Transpose A:
 [[1 3]
 [2 4]]


### MEMBUAT ARRAY MULTIDIMENSI

Array tidak hanya 1D (baris) atau 2D (matriks), tapi juga bisa lebih, misalnya 3D. Array 3D bisa dibayangkan sebagai “tumpukan matriks” yang digunakan dalam data kompleks seperti gambar atau data ilmiah.

In [ ]:
import numpy as np

# Membuat array 3 dimensi
arr3D = np.array([ [[1, 2], [3, 4]],
                   [[5, 6], [7, 8]] ])

print("Array 3D:\n", arr3D)


Array 3D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### MENGETAHUI INDEX ELEMEN PADA ARRAY

Index adalah posisi suatu elemen di dalam array. Dengan np.where(), kita bisa mencari index dari nilai tertentu. Misalnya, angka 30 ada di index ke-2.

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Cari index elemen
index = np.where(arr == 30)
print("Index elemen 30:", index[0][0])


Index elemen 30: 2


### MENGIMPLEMENTASIKAN OPERASI LOGIKA MATEMATIKA MENGGUNAKAN BOOLEAN

Boolean adalah tipe data yang memiliki nilai True (benar) atau False (salah). Maksud dari Mengimplementasikan operasi logika matematika menggunakan Boolean itu, artinya memakai nilai True/False dan operator logika (AND, OR, NOT) untuk mengambil keputusan atau untuk melakukan perhitungannya, contohnya seperti kode dibawah, dan hasil untuk cara kerja operator logika (AND, OR, NOT), seperti dijelaskan disamping kodenya.

In [ ]:
A = (2 > 1)   # True, karena 2 memang lebih besar dari 1
B = (5 < 3)   # False, karena 5 tidak lebih kecil dari 3

print("A =", A)
print("B =", B)
print("A AND B =", A and B)     # AND: True kalau A dan B sama-sama True
print("A OR B  =", A or B)      # OR: True kalau salah satu True
print("NOT A   =", not A)       # NOT: membalik nilai A
print("A -> B  =", (not A) or B) # Implikasi: salah hanya kalau A True dan B False
print("A ↔ B   =", A == B)      # Ekuivalen: True kalau A dan B sama

A = True
B = False
A AND B = False
A OR B  = True
NOT A   = False
A -> B  = False
A ↔ B   = False


### MELAKUKAN OPERASI ARITMATIKA

Operasi aritmatika adalah perhitungan matematika dasar yang kita pakai sehari-hari, seperti tambah, kurang, kali, bagi, dan seterusnya. Melakukan operasi aritmatika artinya menggunakan simbol matematika untuk menghitung angka.
Di pemrograman, kita tinggal pakai operator (+, -, *, /, dll.) agar komputer menghitung otomatis. Contohnya seperti kode dibawah ini:

In [ ]:
# Mendefinisikan Nilainya
apel = 7
jeruk = 9
print("Jumlah Apel: ", apel)
print("Jumlah jeruk: ", jeruk)

# Penjumlahan
jumlah_buah = apel + jeruk
print("Jumlah dari apel dan jeruk adalah", jumlah_buah)

# Pengurangan
selisih_buah = jeruk - apel
print("Selisih dari jumlah jeruk dan apel adalah", selisih_buah)

# Perkalian
perkalian = apel * jeruk
print("Nilai apel x jeruk: ", perkalian)

# Pembagian
pembagian = jeruk/apel
print("Nilai jeruk dibagi apel: ", pembagian)

# Sisa Bagi/Modulus
sisa_bagi = jeruk % apel
print("Sisa bagi dari apel dan jeruk adalah", sisa_bagi)

# Panngkat
pangkat = apel ** jeruk
print("Hasil pangkat dari apel pangkat jeruk adalah", pangkat)

Jumlah Apel:  7
Jumlah jeruk:  9
Jumlah dari apel dan jeruk adalah 16
Selisih dari jumlah jeruk dan apel adalah 2
Nilai apel x jeruk:  63
Nilai jeruk dibagi apel:  1.2857142857142858
Sisa bagi dari apel dan jeruk adalah 2
Hasil pangkat dari apel pangkat jeruk adalah 40353607


### ELEMENTWISE FUNCTIONS

Anggap kita punya daftar angka (misalnya array atau list dalam python).
Elementwise function adalah fungsi yang diterapkan ke setiap elemen di dalam daftar itu, satu per satu, lalu mengembalikan daftar baru dengan hasil yang sama panjang. Intinya Elementwise function adalah fungsi yang bekerja per elemen dari sebuah array/list, lalu mengembalikan array dengan bentuk sama, tanpa perlu kita membuat loop manual. Untuk contoh kodenya seperti dibawah ini:

In [ ]:
import numpy as np

# buat array
a = np.array([3, 6, 9])

# mencari nilai akar kuadrat dari setiap element
print(np.sqrt(a))

# setiap elemen ditambah 10
print(a + 10)

# setiap elemen pakai sin
print(np.sin(a))

[1.73205081 2.44948974 3.        ]
[13 16 19]
[ 0.14112001 -0.2794155   0.41211849]
